Added yml file corresponding to running unit tests in both windows and ubuntu
Maoni0/realmon pull request #10
Opened 2021-11-12 04:21 UTC by MokoSan

Added yml file corresponding to running unit tests in both windows and ubuntu. These test will run for every push and on pull request creation for all branches.

2021-11-12 19:48 UTC, Maoni0 commented
hi @MokoSan, I don't think this needs updates after [this PR](https://github.com/Maoni0/realmon/pull/5) was merged, correct (since the test dir didn't change)? if you could please confirm I will merge this one :)

2021-11-13 04:44 UTC, MokoSan commented
Hey @Maoni0, this PR automates running all the unit tests right after a dev creates a pull request or pushes new changes to all branches to make sure the unit test runs are automated. Please let me know if this isn't needed; I think from the perspective of automated unit testing, it might help capture errors earlier than later. 

An example of a run is:
https://github.com/MokoSan/realmon/runs/4188326247?check_suite_focus=true 

Thanks,
M.

2021-11-13 05:44 UTC, hez2010 requested changes

2021-11-13 05:44 UTC, hez2010 commented on .github/workflows/run_tests.yml
> +  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use
We have bumped dotnet version to `6.0.100` in the latest commit.

```suggestion
  DOTNET_VERSION: '6.0.100' # The .NET SDK version to use
```

2021-11-13 08:05 UTC, Maoni0 commented
yep, I got that the purpose was adding the tests to run automatically and thought it was great to add them. just wanted to make sure that it didn't need any updates after the last commit. I saw that @hez2010 already helped out with that. so that's great! I'll merge. thanks very much for this!

2021-11-13 08:05 UTC, merged

2021-11-13 17:27 UTC, MokoSan commented
> yep, I got that the purpose was adding the tests to run automatically and thought it was great to add them. just wanted to make sure that it didn't need any updates after the last commit. I saw that @hez2010 already helped out with that. so that's great! I'll merge. thanks very much for this!

Thank you @Maoni0 and @hez2010!